### ISSUE TITLE
archive data directly from redwood to Glacier storage

### ISSUE THREAD

**Issue by klearned** [BD2KGenomics/dcc-feature-requests#10]
We want to be able to archive data directly from redwood to AWS Glacier Cloud Storage‎ upon request or after a certain amount of time...e.g. after 1 month, output .bam files are moved to Glacier.

**Comment by klearned** [comment]
@wshands @kozbo

**Comment by wshands** [comment]
Closing since issue added to dcc-storage repo: https://github.com/BD2KGenomics/dcc-storage/issues/27
