### ISSUE TITLE
Wrap command to upload manifest in simpler script

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/dcc-feature-requests#7]
The spinnaker docker command to upload files from an manifest or upload a single file is somewhat complicated for some users; it could perhaps be made simpler by wrapping it in a script

**Comment by klearned** [comment]
...and wrapper for downloading also, please!

**Comment by wshands** [comment]
Closing because an issue was added to the spinnaker client repo: https://github.com/BD2KGenomics/dcc-spinnaker-client/issues/46
