### ISSUE TITLE
pre-beta test feedback/suggestions

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/dcc-feature-requests#9]
[x] moved - each file gets duplicated during the upload process, so it eats into disk space.

[x] moved - Also a pain to go back and clean them all out because they remain there after the upload.

- if this is uploading to s3 buckets, it’s still going at about half the upload speed I get when pushing into s3 (encrypted or not) based on my network traffic speed checks.

- if/when you change columns to the upload manifest template it would be a courtesy for your pre-beta tester to let them know explicitly what changed between the week of previous uploads and this week.

**Comment by wshands** [comment]
Closing since issues added to repos:
https://github.com/BD2KGenomics/dcc-spinnaker-client/issues/47

https://github.com/BD2KGenomics/dcc-spinnaker-client/issues/48
